export const DEFAULT_KEYBINDINGS = {
  bold: 'mod+b',
  italic: 'mod+i',
  underline: 'mod+u',
  strikethrough: 'mod+shift+x',
  undo: 'mod+z',
  redo: 'mod+shift+z',
  selectAll: 'mod+a',
  insertLink: 'mod+k',
  findReplace: 'mod+f',
  orderedList: 'mod+shift+7',
  unorderedList: 'mod+shift+8',
  blockquote: 'mod+shift+9',
  codeBlock: 'mod+shift+c',
  indent: 'tab',
  outdent: 'shift+tab',
  fullscreen: 'mod+shift+f',
  sourceMode: 'mod+shift+u',
  subscript: 'mod+,',
  superscript: 'mod+.',
}
